// AUTO-GENERATED by schema-extractor — do not edit by hand.
export type Uuid = string;
export type Sha1 = string;
export type Semver = string;
export type IsoDate = string;
export type Url = string;
export type Path = string;
export type Blob = string;

/** session_meta */
export type SessionMeta_7c155bf0 = {
  payload: {
    base_instructions: {
      text: Path;
    };
    cli_version: Semver;
    cwd: Path;
    git: {
      branch: string;
      commit_hash: Sha1;
      repository_url: Url;
    };
    id: Uuid;
    model_provider: string;
    originator: string;
    source: string;
    timestamp: IsoDate;
  };
  timestamp: IsoDate;
  type: "session_meta";
};

/** event_msg.payload -> task_started */
export type Payload_TaskStarted_a4b2ab3a = {
  collaboration_mode_kind: string;
  model_context_window: number;
  started_at: number;
  turn_id: Uuid;
  type: "task_started";
};

/** event_msg.payload -> user_message */
export type Payload_UserMessage_483c31dd = {
  images: never[];
  local_images: never[];
  message: string;
  text_elements: never[];
  type: "user_message";
};

/** event_msg.payload -> token_count.info -> Variant.last_token_usage -> Variant */
export type TotalTokenUsage_Type_2c77a36c = {
  cached_input_tokens: number;
  input_tokens: number;
  output_tokens: number;
  reasoning_output_tokens: number;
  total_tokens: number;
};

/** event_msg.payload -> token_count.info -> Variant */
export type Info_Variant_9c866fce = {
  last_token_usage: TotalTokenUsage_Type_2c77a36c;
  model_context_window: number;
  total_token_usage: TotalTokenUsage_Type_2c77a36c;
};

/** event_msg.payload -> token_count.rate_limits.credits -> Variant */
export type Credits_Variant_0e28e753 = {
  balance: null;
  has_credits: boolean;
  unlimited: boolean;
};

/** event_msg.payload -> token_count.rate_limits.primary -> Variant */
export type Primary_Type_aec06b40 = {
  resets_at: number;
  used_percent: number;
  window_minutes: number;
};

/** event_msg.payload -> token_count */
export type Payload_TokenCount_0b236b38 = {
  info: null | Info_Variant_9c866fce;
  rate_limits: {
    credits: null | Credits_Variant_0e28e753;
    limit_id: string;
    limit_name: null;
    plan_type: string | null;
    primary: Primary_Type_aec06b40;
    rate_limit_reached_type: null;
    secondary: {
      resets_at: number;
      used_percent: number;
      window_minutes: number;
    };
  };
  type: "token_count";
};

/** event_msg.payload -> agent_message */
export type Payload_AgentMessage_b4549732 = {
  memory_citation: null;
  message: Blob;
  phase: string;
  type: "agent_message";
};

/** event_msg.payload -> exec_command_end.parsed_cmd[] -> unknown */
export type ParsedCmd_Unknown_d14863f0 = {
  cmd: string;
  type: "unknown";
};

/** event_msg.payload -> exec_command_end.parsed_cmd[] -> list_files */
export type ParsedCmd_ListFiles_e2e8023d = {
  cmd: string;
  path: string | null;
  type: "list_files";
};

/** event_msg.payload -> exec_command_end.parsed_cmd[] -> search */
export type ParsedCmd_Search_21239ceb = {
  cmd: string;
  path: string;
  query: string;
  type: "search";
};

/** event_msg.payload -> exec_command_end.parsed_cmd[] -> read */
export type ParsedCmd_Read_ecb7620b = {
  cmd: string;
  name: string;
  path: string;
  type: "read";
};

/** event_msg.payload -> exec_command_end */
export type Payload_ExecCommandEnd_6188387d = {
  aggregated_output: string;
  call_id: string;
  command: string[];
  cwd: Path;
  duration: {
    nanos: number;
    secs: number;
  };
  exit_code: number;
  formatted_output: string;
  parsed_cmd: Array<ParsedCmd_Unknown_d14863f0 | ParsedCmd_ListFiles_e2e8023d | ParsedCmd_Search_21239ceb | ParsedCmd_Read_ecb7620b>;
  process_id: string;
  source: string;
  status: string;
  stderr: string;
  stdout: string;
  turn_id: Uuid;
  type: "exec_command_end";
};

/** event_msg.payload -> task_complete */
export type Payload_TaskComplete_65e6b772 = {
  completed_at: number;
  duration_ms: number;
  last_agent_message: Blob | null;
  time_to_first_token_ms: number;
  turn_id: Uuid;
  type: "task_complete";
};

/** event_msg.payload -> patch_apply_end.changes{} -> add */
export type Changes_Add_6aafb9d5 = {
  content: Blob;
  type: "add";
};

/** event_msg.payload -> patch_apply_end.changes{} -> update */
export type Changes_Update_36b7f96d = {
  move_path: null;
  type: "update";
  unified_diff: string;
};

/** event_msg.payload -> patch_apply_end */
export type Payload_PatchApplyEnd_df3fe0f8 = {
  call_id: string;
  changes: Record<Path, Changes_Add_6aafb9d5 | Changes_Update_36b7f96d>;
  status: string;
  stderr: string;
  stdout: Path;
  success: boolean;
  turn_id: Uuid;
  type: "patch_apply_end";
};

/** event_msg.payload -> turn_aborted */
export type Payload_TurnAborted_1b096623 = {
  completed_at: number;
  duration_ms: number;
  reason: string;
  turn_id: Uuid;
  type: "turn_aborted";
};

/** event_msg.payload -> item_completed */
export type Payload_ItemCompleted_79dd0913 = {
  item: {
    id: string;
    text: Path;
    type: "Plan";
  };
  thread_id: Uuid;
  turn_id: Uuid;
  type: "item_completed";
};

/** event_msg */
export type EventMsg_8c542c2c = {
  payload: Payload_TaskStarted_a4b2ab3a | Payload_UserMessage_483c31dd | Payload_TokenCount_0b236b38 | Payload_AgentMessage_b4549732 | Payload_ExecCommandEnd_6188387d | Payload_TaskComplete_65e6b772 | Payload_PatchApplyEnd_df3fe0f8 | Payload_TurnAborted_1b096623 | Payload_ItemCompleted_79dd0913;
  timestamp: IsoDate;
  type: "event_msg";
};

/** response_item.payload -> message */
export type Payload_Message_d31625e1 = {
  content: {
    text: string;
    type: "input_text";
  }[];
  role: "developer";
  type: "message";
};

/** response_item.payload -> message */
export type Payload_Message_d31625e1_2 = {
  content: {
    text: string;
    type: "input_text";
  }[];
  role: "user";
  type: "message";
};

/** response_item.payload -> reasoning */
export type Payload_Reasoning_30b4aaaf = {
  content: null;
  encrypted_content: Blob;
  summary: never[];
  type: "reasoning";
};

/** response_item.payload -> message */
export type Payload_Message_d31625e1_3 = {
  content: {
    text: string;
    type: "output_text";
  }[];
  phase: string;
  role: "assistant";
  type: "message";
};

/** response_item.payload -> function_call */
export type Payload_FunctionCall_dcd8c4bc = {
  arguments: Blob;
  call_id: string;
  name: string;
  type: "function_call";
};

/** response_item.payload -> function_call_output */
export type Payload_FunctionCallOutput_d57ef584 = {
  call_id: string;
  output: Blob;
  type: "function_call_output";
};

/** response_item.payload -> custom_tool_call */
export type Payload_CustomToolCall_62ba07c8 = {
  call_id: string;
  input: Path;
  name: string;
  status: string;
  type: "custom_tool_call";
};

/** response_item.payload -> custom_tool_call_output */
export type Payload_CustomToolCallOutput_8edc46ca = {
  call_id: string;
  output: Path;
  type: "custom_tool_call_output";
};

/** response_item */
export type ResponseItem_8b8f7924 = {
  payload: Payload_Message_d31625e1 | Payload_Message_d31625e1_2 | Payload_Reasoning_30b4aaaf | Payload_Message_d31625e1_3 | Payload_FunctionCall_dcd8c4bc | Payload_FunctionCallOutput_d57ef584 | Payload_CustomToolCall_62ba07c8 | Payload_CustomToolCallOutput_8edc46ca;
  timestamp: IsoDate;
  type: "response_item";
};

/** turn_context.payload.file_system_sandbox_policy.entries[].path -> special.value -> root */
export type Value_Root_247a87ca = {
  kind: "root";
};

/** turn_context.payload.file_system_sandbox_policy.entries[].path -> special.value -> project_roots */
export type Value_ProjectRoots_5e5fa8ed = {
  kind: "project_roots";
  subpath?: string;
};

/** turn_context.payload.file_system_sandbox_policy.entries[].path -> special.value -> slash_tmp */
export type Value_SlashTmp_876957b0 = {
  kind: "slash_tmp";
};

/** turn_context.payload.file_system_sandbox_policy.entries[].path -> special.value -> tmpdir */
export type Value_Tmpdir_8c4bad16 = {
  kind: "tmpdir";
};

/** turn_context.payload.file_system_sandbox_policy.entries[].path -> special */
export type Path_Special_a180aa3f = {
  type: "special";
  value: Value_Root_247a87ca | Value_ProjectRoots_5e5fa8ed | Value_SlashTmp_876957b0 | Value_Tmpdir_8c4bad16;
};

/** turn_context.payload.file_system_sandbox_policy.entries[].path -> path */
export type Path_Path_1e73cb58 = {
  path: Path;
  type: "path";
};

/** turn_context.payload.permission_profile.file_system.entries[] -> Variant */
export type Entries_Type_b768ea2a = {
  access: string;
  path: Path_Special_a180aa3f | Path_Path_1e73cb58;
};

/** turn_context */
export type TurnContext_0f2a906e = {
  payload: {
    approval_policy: string;
    collaboration_mode: {
      mode: string;
      settings: {
        developer_instructions: Path;
        model: string;
        reasoning_effort: string;
      };
    };
    current_date: IsoDate;
    cwd: Path;
    effort: string;
    file_system_sandbox_policy: {
      entries: {
        access: string;
        path: Path_Special_a180aa3f | Path_Path_1e73cb58;
      }[];
      kind: "restricted";
    };
    model: string;
    permission_profile: {
      file_system: {
        entries: Entries_Type_b768ea2a[];
        type: "restricted";
      };
      network: string;
      type: "managed";
    };
    personality: string;
    realtime_active: boolean;
    sandbox_policy: {
      exclude_slash_tmp: boolean;
      exclude_tmpdir_env_var: boolean;
      network_access: boolean;
      type: "workspace-write";
      writable_roots: Path[];
    };
    summary: string;
    timezone: Path;
    truncation_policy: {
      limit: number;
      mode: string;
    };
    turn_id: Uuid;
  };
  timestamp: IsoDate;
  type: "turn_context";
};

export type CodexRollout = SessionMeta_7c155bf0 | EventMsg_8c542c2c | ResponseItem_8b8f7924 | TurnContext_0f2a906e;
