// AUTO-GENERATED by schema-extractor — do not edit by hand.
export type ModelId = string;
export type Uuid = string;
export type Semver = string;
export type IsoDate = string;
export type Path = string;
export type Blob = string;

/** session.start */
export type SessionStart_ae3f67f4 = {
  data: {
    alreadyInUse: boolean;
    context: {
      cwd: Path;
    };
    copilotVersion: Semver;
    producer: string;
    remoteSteerable: boolean;
    sessionId: Uuid;
    startTime: IsoDate;
    version: number;
  };
  id: Uuid;
  parentId: null;
  timestamp: IsoDate;
  type: "session.start";
};

/** session.model_change */
export type SessionModelChange_6e9905c3 = {
  data: {
    newModel: ModelId;
  };
  id: Uuid;
  parentId: Uuid;
  timestamp: IsoDate;
  type: "session.model_change";
};

/** system.message */
export type SystemMessage_a93737ed = {
  data: {
    content: Path;
    role: "system";
  };
  id: Uuid;
  parentId: Uuid;
  timestamp: IsoDate;
  type: "system.message";
};

/** user.message */
export type UserMessage_f711d7d4 = {
  data: {
    attachments: never[];
    content: Path;
    interactionId: Uuid;
    parentAgentTaskId: Uuid;
    supportedNativeDocumentMimeTypes: never[];
    transformedContent: Path;
  };
  id: Uuid;
  parentId: Uuid;
  timestamp: IsoDate;
  type: "user.message";
};

/** assistant.turn_start */
export type AssistantTurnStart_3f2b3834 = {
  data: {
    interactionId: Uuid;
    turnId: string;
  };
  id: Uuid;
  parentId: Uuid;
  timestamp: IsoDate;
  type: "assistant.turn_start";
};

/** assistant.message.data.toolRequests[].arguments -> Variant */
export type Arguments_Variant_1be55992 = {
  intent: string;
};

/** assistant.message.data.toolRequests[].arguments -> Variant */
export type Arguments_Shared_cc9fa6c4 = {
  file_text?: string;
  path: Path;
};

/** assistant.message.data.toolRequests[].arguments -> Variant */
export type Arguments_Shared_856b2c6e = {
  command: string;
  description: string;
};

/** assistant.message.data.toolRequests[].arguments -> Variant */
export type Arguments_Shared_aed4dd98 = {
  new_str: string;
  old_str: string;
  path: Path;
};

/** assistant.message */
export type AssistantMessage_e660180a = {
  data: {
    content: string;
    interactionId: Uuid;
    messageId: Uuid;
    model: ModelId;
    outputTokens: number;
    toolRequests: {
      arguments: Arguments_Variant_1be55992 | Arguments_Shared_cc9fa6c4 | Arguments_Shared_856b2c6e | Arguments_Shared_aed4dd98;
      intentionSummary?: string;
      name: string;
      toolCallId: string;
      type: "function";
    }[];
    turnId: string;
  };
  id: Uuid;
  parentId: Uuid;
  timestamp: IsoDate;
  type: "assistant.message";
};

/** tool.execution_start */
export type ToolExecutionStart_218c74d0 = {
  data: {
    arguments: Arguments_Variant_1be55992 | Arguments_Shared_cc9fa6c4 | Arguments_Shared_856b2c6e | Arguments_Shared_aed4dd98;
    toolCallId: string;
    toolName: string;
    turnId: string;
  };
  id: Uuid;
  parentId: Uuid;
  timestamp: IsoDate;
  type: "tool.execution_start";
};

/** hook.start.data.input.toolResult.toolTelemetry -> Variant.metrics -> Variant */
export type Metrics_Variant_071858b0 = {
  linesAdded?: number;
  linesRemoved?: number;
  responseTokenLimit: number;
  resultForLlmLength: number;
  resultLength: number;
};

/** hook.start.data.input.toolResult.toolTelemetry -> Variant.metrics -> Variant */
export type Metrics_Variant_071858b0_2 = {
  commandTimeout: number;
};

/** hook.start.data.input.toolResult.toolTelemetry -> Variant.properties -> Variant */
export type Properties_Shared_c67a4e5f = {
  command: string;
  fileExtension: string;
  inputs: string;
  options: Blob;
  resolvedPathAgainstCwd: string;
  viewType: string;
};

/** hook.start.data.input.toolResult.toolTelemetry -> Variant.properties -> Variant */
export type Properties_Variant_e63f2fa0 = {
  codeBlocks: Blob;
  command: string;
  fileExtension: string;
  inputs: string;
  languageId: string;
  options: Blob;
  resolvedPathAgainstCwd: string;
};

/** hook.start.data.input.toolResult.toolTelemetry -> Variant.properties -> Variant */
export type Properties_Variant_e63f2fa0_2 = {
  customTimeout: string;
  detached: string;
  executionMode: string;
};

/** hook.start.data.input.toolResult.toolTelemetry -> Variant */
export type ToolTelemetry_Type_e710da11 = {
  metrics?: Metrics_Variant_071858b0 | Metrics_Variant_071858b0_2;
  properties?: Properties_Shared_c67a4e5f | Properties_Variant_e63f2fa0 | Properties_Variant_e63f2fa0_2;
  restrictedProperties?: {
    filePaths?: Path;
  };
};

/** hook.start */
export type HookStart_3b05588d = {
  data: {
    hookInvocationId: Uuid;
    hookType: string;
    input: {
      cwd: Path;
      sessionId: Uuid;
      timestamp: number;
      toolArgs: Arguments_Variant_1be55992 | Arguments_Shared_856b2c6e | Arguments_Shared_cc9fa6c4 | Arguments_Shared_aed4dd98;
      toolName: string;
      toolResult: {
        resultType: string;
        sessionLog: string;
        skipLargeOutputProcessing?: boolean;
        textResultForLlm: string;
        toolTelemetry: ToolTelemetry_Type_e710da11;
      };
    };
  };
  id: Uuid;
  parentId: Uuid;
  timestamp: IsoDate;
  type: "hook.start";
};

/** hook.end */
export type HookEnd_1fefd357 = {
  data: {
    hookInvocationId: Uuid;
    hookType: string;
    success: boolean;
  };
  id: Uuid;
  parentId: Uuid;
  timestamp: IsoDate;
  type: "hook.end";
};

/** tool.execution_complete.data -> Variant */
export type Data_Variant_c999eaf2 = {
  interactionId: Uuid;
  model: ModelId;
  result: {
    content: string;
    detailedContent: string;
  };
  success: boolean;
  toolCallId: string;
  toolTelemetry: ToolTelemetry_Type_e710da11;
  turnId: string;
};

/** tool.execution_complete.data -> Variant */
export type Data_Variant_c999eaf2_2 = {
  error: {
    code: string;
    message: string;
  };
  interactionId: Uuid;
  model: ModelId;
  success: boolean;
  toolCallId: string;
  toolTelemetry: {
    metrics: {
      responseTokenLimit: number;
      resultForLlmLength: number;
      resultLength: number;
    };
    properties: Properties_Shared_c67a4e5f;
    restrictedProperties: Record<string, unknown>;
  };
  turnId: string;
};

/** tool.execution_complete */
export type ToolExecutionComplete_bbfd4911 = {
  data: Data_Variant_c999eaf2 | Data_Variant_c999eaf2_2;
  id: Uuid;
  parentId: Uuid;
  timestamp: IsoDate;
  type: "tool.execution_complete";
};

/** assistant.turn_end */
export type AssistantTurnEnd_fca6402c = {
  data: {
    turnId: string;
  };
  id: Uuid;
  parentId: Uuid;
  timestamp: IsoDate;
  type: "assistant.turn_end";
};

/** session.shutdown */
export type SessionShutdown_51fb1028 = {
  data: {
    codeChanges: {
      filesModified: Path[];
      linesAdded: number;
      linesRemoved: number;
    };
    conversationTokens: number;
    currentModel: ModelId;
    currentTokens: number;
    modelMetrics: Record<ModelId, {
      requests: {
        cost: number;
        count: number;
      };
      usage: {
        cacheReadTokens: number;
        cacheWriteTokens: number;
        inputTokens: number;
        outputTokens: number;
        reasoningTokens: number;
      };
    }>;
    sessionStartTime: number;
    shutdownType: string;
    systemTokens: number;
    toolDefinitionsTokens: number;
    totalApiDurationMs: number;
    totalPremiumRequests: number;
  };
  id: Uuid;
  parentId: Uuid;
  timestamp: IsoDate;
  type: "session.shutdown";
};

export type CopilotCli = SessionStart_ae3f67f4 | SessionModelChange_6e9905c3 | SystemMessage_a93737ed | UserMessage_f711d7d4 | AssistantTurnStart_3f2b3834 | AssistantMessage_e660180a | ToolExecutionStart_218c74d0 | HookStart_3b05588d | HookEnd_1fefd357 | ToolExecutionComplete_bbfd4911 | AssistantTurnEnd_fca6402c | SessionShutdown_51fb1028;
