// AUTO-GENERATED by schema-extractor — do not edit by hand.
export type Deep = {
  a: {
    b: {
      c: {
        d: {
          e: {
            f: {
              g: {
                h: {
                  i: {
                    j: {
                      k: {
                        l: number;
                      };
                    };
                  };
                };
              };
            };
          };
        };
      };
    };
  };
};
