// AUTO-GENERATED by schema-extractor — do not edit by hand.
/** Variant */
export type Variant_4fb0aea8 = {
  a: number;
  b: null;
  c?: string | null;
  d?: boolean;
};

/** Variant */
export type Variant_4fb0aea8_2 = {
  a: number;
  c: string;
  d: boolean;
};

export type Mixed = Variant_4fb0aea8 | Variant_4fb0aea8_2;
