// AUTO-GENERATED by schema-extractor — do not edit by hand.
/** events[] -> start */
export type Events_Start_b03a7317 = {
  type: "start";
};

/** events[] -> data */
export type Events_Data_f5a8ca19 = {
  payload: string;
  type: "data";
};

/** events[] -> end */
export type Events_End_c0330d11 = {
  code: number;
  type: "end";
};

export type Root = {
  events: Array<Events_Start_b03a7317 | Events_Data_f5a8ca19 | Events_End_c0330d11>;
};
