// AUTO-GENERATED by schema-extractor — do not edit by hand.
export type ModelId = string;

export type Root = {
  modelMetrics: Record<ModelId, {
    cost?: number;
    count: number;
  }>;
  "system-reminder": {
    text: string;
  };
};
