// AUTO-GENERATED by schema-extractor — do not edit by hand.
/** root.children[] -> 1.children[] -> 2 */
export type Children_2_8d94623f = {
  text: string;
  type: 2;
};

/** root.children[] -> 1 */
export type Children_1_b840131d = {
  children: Array<Children_1_b840131d | Children_2_8d94623f>;
  name: string;
  type: 1;
};

export type Doc = {
  root: {
    children: Array<Children_1_b840131d | Children_2_8d94623f>;
    name: string;
    type: 1;
  };
};
