// AUTO-GENERATED by schema-extractor — do not edit by hand.
/** response[] -> pts.content -> Variant */
export type Content_Variant_dcefac79 = {
  uris: Record<string, unknown>;
  value: string;
};

/** response[] -> pts.content -> Variant */
export type Content_Variant_dcefac79_2 = {
  isTrusted: boolean;
  supportThemeIcons: boolean;
  value: string;
};

/** response[] -> pts */
export type Response_Pts_cf4de7aa = {
  content: Content_Variant_dcefac79 | Content_Variant_dcefac79_2;
  kind: "pts";
};

/** response[] -> other */
export type Response_Other_3b07d6bd = {
  kind: "other";
  x: number;
};

export type Evt = {
  response: Array<Response_Pts_cf4de7aa | Response_Other_3b07d6bd>;
};
