// AUTO-GENERATED by schema-extractor — do not edit by hand.
/** a */
export type A_992a2927 = {
  type: "a";
  x: number;
  x2?: string;
};

/** b */
export type B_dcc594c7 = {
  type: "b";
  y: string;
};

/** c */
export type C_d6fd4188 = {
  type: "c";
  z: number[];
};

export type Evt = A_992a2927 | B_dcc594c7 | C_d6fd4188;
