// AUTO-GENERATED by schema-extractor — do not edit by hand.
export type IsoDate = string;

/** messages[] -> user */
export type Messages_User_7fca3045 = {
  content: string;
  role: "user";
};

/** messages[] -> assistant */
export type Messages_Assistant_18c41ba3 = {
  content: string;
  role: "assistant";
  toolCalls: never[];
};

export type Session = {
  messages: Array<Messages_User_7fca3045 | Messages_Assistant_18c41ba3>;
  meta: {
    createdAt: IsoDate;
    title: string;
  };
  version: number;
};
