import { activeAliases } from "@/ir/alias"
import type { DeclEntry, EmitCtx } from "./render"

export function formatDoc(paths: string[]): string {
  if (paths.length === 0) return ""
  if (paths.length === 1) return `/** ${paths[0]} */\n`
  return `/**\n${paths.map((p) => ` * ${p}`).join("\n")}\n */\n`
}

export function buildDocument(opts: {
  ctx: EmitCtx
  decls: DeclEntry[]
  rootName: string
  renderedRoot: string
  header?: string
}): string {
  const { ctx, decls, rootName, renderedRoot } = opts
  const header = opts.header ?? `// AUTO-GENERATED by schema-extractor — do not edit by hand.\n`
  const aliasDecls: string[] = []
  for (const def of activeAliases()) {
    if (ctx.aliases.has(def.name)) aliasDecls.push(`export type ${def.name} = string;`)
  }
  if (ctx.aliases.has("Blob")) aliasDecls.push("export type Blob = string;")
  const aliasBlock = aliasDecls.length ? `${aliasDecls.join("\n")}\n\n` : ""
  const declStrings = decls.map((d) => `${formatDoc(d.doc)}export type ${d.name} = ${d.body};`)
  return (
    header +
    aliasBlock +
    declStrings.join("\n\n") +
    (declStrings.length ? "\n\n" : "") +
    `export type ${rootName} = ${renderedRoot};\n`
  )
}
